name: Docker Image CI Staging

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            -   name: Build and push docker image
                uses: docker/build-push-action@v1
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    dockerfile: Dockerfile
                    repository: avikhlyaeva/img-game-frontend
                    tags: staging
